name: Elíseo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Instalar dependencias
        working-directory: mobile
        run: npm ci

      - name: Liberar Gradle
        run: chmod +x mobile/android/gradlew

      - name: Gerar APK
        working-directory: mobile/android
        run: ./gradlew assembleRelease --stacktrace

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: eliseo
          path: mobile/android/app/build/outputs/apk/release/*.apk
